name: 'novellidbt'
version: '1.0.0'
config-version: 2

profile: 'novelli'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"

models:
  novellidbt:
    wrike:
      +materialized: view
      +schema: wrike
    hubspot:
      +materialized: view
      +schema: hubspot
    xero:
      +materialized: view
      +schema: xero